### ISSUE TITLE
Unable to include in my plugin

### ISSUE THREAD

**Issue by vaclavgreif** [stylesplugin/styles-font-menu#6]
I added to my plugin

`
require_once('lib/styles-font-menu/plugin.php');
`
and than in my template I added:

`
<?php
            if(has_action('styles_font_menu')) {
                // action exists so execute it
                do_action('styles_font_menu');
            } else {
                echo 'No styles menu action!';
            }
            ?>
`

Which return 'No styles menu action'. Anything else is needed to have the action included?

**Comment by pdclark** [comment]
`has_action` is used for special cases where you want to check if a specific function has been _attached_ to a specific action.

`do_action` runs the appropriate checks for actions to run automatically. So, it should not be used with a wrapper like `has_action` or `function_exists` — it fails gracefully.

So instead of this in your template:

``` php
 <?php
if(has_action('styles_font_menu')) {
    // action exists so execute it
    do_action('styles_font_menu');
} else {
    echo 'No styles menu action!';
}
?>
```

You should have this:

``` php
<?php do_action( 'styles_font_menu' ); ?>
```

See http://codex.wordpress.org/Function_Reference/has_action and http://nacin.com/2010/05/18/rethinking-template-tags-in-plugins/

**Comment by vaclavgreif** [comment]
Thanks, I tried that first, and now again, but I still don't get any output...

**Comment by vaclavgreif** [comment]
Hmmm, I investigated more, and to display the dropdown in my template I had to remove:

`apply_filters( 'styles_font_menu_include_on_frontend', is_admin() )`

from plugin.php. I have no idea why this happens...

**Comment by pdclark** [comment]
Ah, yes. Sorry about that — it's disabled on front-end by default. If I remember correctly, it was to maximize performance, since most plugins and themes would use it in `wp-admin` or the theme customizer.

You don't need to edit the core code. Instead, use this to toggle the filter in your theme's `functions.php`:

``` php
add_filter( 'styles_font_menu_include_on_frontend', '__return_true' );
```

Note the comment above [that line](https://github.com/stylesplugin/styles-font-menu/blob/master/plugin.php#L19):

``` php
/**
 * Only include library in admin by default. Override with the filter
 * 
 * @example add_filter( 'styles_font_menu_include_on_frontend', '__return_true' );
 */
```

**Comment by vaclavgreif** [comment]
Thanks!
